### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getFile' of undefined

### ISSUE THREAD

**Issue by FinnAylar** [THM-MoTE/mope-atom-plugin#4]
1. Opened project folder
2. used command "Mope: Generate Project.json"

**Atom**: 1.50.0 x64
**Electron**: 5.0.13
**OS**: Ubuntu 16.04.7
**Thrown From**: [MoPE](https://github.com/THM-MoTE/mope-atom-plugin) package 0.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getFile' of undefined

```
At /home/blesius/.atom/packages/MoPE/lib/moie.js:321

TypeError: Cannot read property 'getFile' of undefined
    at Object.generateProjectConfig (/packages/MoPE/lib/moie.js:321:29)
    at HTMLElement.mopeGenerateProjectJson (/packages/MoPE/lib/moie.js:71:48)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:349780)
    at Object.didConfirmSelection (/usr/share/atom/resources/app/static/<embedded>:11:683764)
    at SelectListView.confirmSelection (/usr/share/atom/resources/app/static/<embedded>:11:855324)
    at HTMLDivElement.core:confirm (/usr/share/atom/resources/app/static/<embedded>:11:850203)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:349780)
    at KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:1230988)
    at KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:11:1227122)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/static/<embedded>:11:284829)
```

### Commands

```
     -1:22.7.0 application:add-project-folder (atom-pane.pane.active)
     -0:51.5.0 command-palette:toggle (input.hidden-input)
     -0:44 core:confirm (input.hidden-input)
     -0:43.8.0 mope:generate-project.json (input.hidden-input)
```

### Non-Core Packages

```
hyperclick 0.1.5 
language-modelica 0.5.1 
MoPE 0.2.0 
```

**Comment by CSchoel** [comment]
Can confirm: "Mope: Generate Project.json" is broken

Until this is fixed, you have to create your `mope-project.json` manually:

```json
{
	"path": "/absolute/path/to/project/dir",
	"outputDirectory": "target"
}
```

**Comment by CSchoel** [comment]
Looks like I found the culprit:

We register the command as

```js
'mope:generate-project.json': () => this.generateProjectConfig()
```

but the signature of that function is

```js
generateProjectConfig(projectDir) {
...
}
```

Therefore, I think we might need something akin to what we do in the `connect()` function for an empty argument:

```js
generateProjectConfig(projectDir) {
  if(projectDir === undefined) {
    projectDir = this.selectProject(atom.project.getDirectories())
  }
  ...
}
```

However, I currently do not have neither the time nor expertise to test if this change fixes the problem and to publish a new version of the plugin.

**Comment by CSchoel** [comment]
@cifland Any chance that you can take a quick look into this issue?
